Repository andela/blackninjas-frontend, pull requests merged in 2020-03, with the labels that each got.

#23 #169817821:user role settings
  .env
  .eslintrc.json
  __mockData__/userRoleSetting.mock.js
  __tests__/_userRoleSettingTest_/actions/userRoleAction.test.js
  __tests__/_userRoleSettingTest_/components/roleSetting.test.js
  __tests__/_userRoleSettingTest_/reducers/UserRoleSettingReducers.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  package.json
  src/actions/UserRoleSettingAction.js
  src/components/App.jsx
  src/components/profile/Nav.links.jsx
  src/components/user/userRole.jsx
  src/helpers/tokenHelper.js
  src/index.js
  src/layouts/default.layout.jsx
  src/layouts/main.layout.jsx
  src/reducers/UserSettingReducer.js
  src/reducers/index.js
  src/styles/userRole.js
Labels: ready for review

#25 #169817824 Implementing tripRequest comments
  __tests__/comments/actions.test.js
  __tests__/comments/comments.view.test.js
  __tests__/comments/reducers.test.js
  __tests__/signup/signupAction.test.js
  __tests__/userTripRequests/tripRequest.view.test.js
  package.json
  src/actions/requests/commentsAction.js
  src/components/comments/comments.view.jsx
  src/reducers/index.js
  src/reducers/trip_requests/commentsReducers.js
  src/theme.js
  src/views/trip_requests/userTripRequest.view.jsx
  src/views/trip_requests/userTripRequests.view.jsx
Labels: completed

#20 #169817818 adding notification pane
  __mockData__/notification.mock.data.js
  __mockData__/redux-mock-data.js
  __tests__/components/__snapshots__/editProfile/__snapshots__/top.navbar.test.js.snap
  __tests__/components/__snapshots__/editProfile/__snapshots__/user.profile.test.js.snap
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/components/__snapshots__/editProfile/top.navbar.test.js
  __tests__/components/__snapshots__/editProfile/user.profile.test.js
  __tests__/notification.pane/__mocks__/socket.io-client.js
  __tests__/notification.pane/notification.action.test.js
  __tests__/notification.pane/notification.component.test.js
  __tests__/notification.pane/notification.reducer.test.js
  __tests__/signup/ActivateUser.view.test.js
  __tests__/signup/signup.view.test.js
  jest.config.js
  package.json
  src/actions/UserRoleSettingAction.js
  src/actions/notificationPane.js
  src/components/auth/ProtectedRoute.jsx
  src/components/notification/notificationPane.jsx
  src/components/profile/Nav.links.jsx
  src/components/profile/Profile.jsx
  src/components/profile/top.nav.bar.jsx
  src/components/profile/userProfile.jsx
  src/components/user/userRole.jsx
  src/index.html
  src/reducers/index.js
  src/reducers/notification.reducer.js
  src/reducers/signInReducer.js
  src/styles/index.scss
  src/styles/notification/notification.scss
Labels: ready for review

#22 #171351272 Implement admin assign users managers
  .travis.yml
  __mockData__/usermanagementMock.js
  __tests__/Footer.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  __tests__/userManagements/userManagement.test.js
  __tests__/userManagements/usermanagementActions.test.js
  __tests__/userManagements/usermanagementReducers.test.js
  package.json
  src/actions/userManagementAction.js
  src/components/auth/Login.jsx
  src/components/common/footer.js
  src/components/profile/Nav.links.jsx
  src/components/user/userRole.jsx
  src/components/usermanagements/UserManagement.jsx
  src/helpers/verifyToken.js
  src/layouts/main.layout.jsx
  src/reducers/index.js
  src/reducers/userManagementReducers.js
  src/store/index.js
  src/styles/profile/cursor
  src/styles/userManagementStyles.js
Labels: ready for review

#13 #171233191 user create one way trip
  __mockData__/tripRequest-mock-data.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  __tests__/tripRequestTest/tripRequestAction.test.js
  __tests__/tripRequestTest/tripRequestForm.test.js
  __tests__/tripRequestTest/tripRequestPicture.js
  __tests__/tripRequestTest/tripRequestReducer.test.js
  __tests__/tripRequestTest/tripRequestView.test.js
  package.json
  src/actions/tripRequestAction.js
  src/components/App.jsx
  src/components/profile/Nav.links.jsx
  src/components/trip-request/adsPictures.jsx
  src/components/trip-request/oneWay.jsx
  src/index.html
  src/layouts/main.layout.jsx
  src/reducers/index.js
  src/reducers/tripRequestReducer.js
  src/theme.js
  src/views/triprequest.view.jsx
Labels: completed, ready for review

#26 #171233149 user create round trip
  __tests__/tripRequestTest/tripRequestView.test.js
  src/actions/tripRequestAction.js
  src/components/trip-request/oneWay.jsx
  src/views/triprequest.view.jsx
Labels: completed, ready for review

#29 #169817818 adding approvals table
  .env
  __mockData__/approval.table.js
  __tests__/approvals_table.js/approval.table.action.test.js
  __tests__/approvals_table.js/approval.table.reducer.test.js
  __tests__/approvals_table.js/approvalsTable.test.js
  __tests__/approvals_table.js/tripRequest.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  __tests__/userTripRequests/reducers.test.js
  __tests__/userTripRequests/tripRequest.view.test.js
  __tests__/userTripRequests/tripRequests.view.test.js
  package.json
  src/actions/approval.table.js
  src/actions/requests/tripRequestsAction.js
  src/components/approvals_table/approval.table.jsx
  src/components/approvals_table/trip.request.jsx
  src/components/comments/comments.view.jsx
  src/components/profile/Nav.links.jsx
  src/components/trip-request/oneWay.jsx
  src/layouts/main.layout.jsx
  src/reducers/approval.table.reducer.js
  src/reducers/index.js
  src/reducers/trip_requests/tripRequestsReducers.js
  src/views/trip_requests/userTripRequest.view.jsx
  src/views/trip_requests/userTripRequests.view.jsx
Labels: completed, ready for review

#31 #169817844 Users should be able to see his/her trip statistics
  __tests__/_userRoleSettingTest_/actions/userRoleAction.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  __tests__/signup/signupAction.test.js
  __tests__/tripRequestTest/tripRequestAction.test.js
  __tests__/userManagements/userManagement.test.js
  __tests__/userStats/userStats.test.js
  __tests__/userStats/userStatsAction.test.js
  __tests__/userStats/userStatsReducer.test.js
  src/actions/tripStatsActions.js
  src/assets/multi.png
  src/assets/oneway.png
  src/assets/return.png
  src/components/UserStatistics.jsx
  src/components/profile/Nav.links.jsx
  src/layouts/main.layout.jsx
  src/reducers/UserSettingReducer.js
  src/reducers/index.js
  src/reducers/tripStatisticsReducer.js
  src/styles/userManagementStyles.js
  src/styles/userStats/userStatsStyles.js
  src/theme.js
Labels: ready for review

#28 #171233214 A user can request a multi-city trip
  __mockData__/tripRequest-mock-data.js
  __tests__/tripRequestTest/tripRequestForm.test.js
  __tests__/tripRequestTest/tripRequestPicture.js
  __tests__/tripRequestTest/tripRequestView.test.js
  src/components/trip-request/adsPictures.jsx
  src/components/trip-request/oneWay.jsx
  src/views/triprequest.view.jsx
Labels: completed, ready for review

#27 #169817835:create accommodations
  __mockData__/accommodationFacility.mock.js
  __mockData__/userRoleSetting.mock.js
  __tests__/___AccommodationFacilities__/Actions/creacteAccomodationAction.test.js
  __tests__/___AccommodationFacilities__/Componentds/Accommodation_facility.test.js
  __tests__/___AccommodationFacilities__/Componentds/Create_accommodation_facility.test.js
  __tests__/___AccommodationFacilities__/Componentds/RoomCard.test.js
  __tests__/___AccommodationFacilities__/Componentds/ServiceCard.test.js
  __tests__/___AccommodationFacilities__/Componentds/UploadRoomImage.test.js
  __tests__/___AccommodationFacilities__/Componentds/__snapshots__/UploadRoomImage.test.js.snap
  __tests__/___AccommodationFacilities__/Reducers/AccommodationFacilitiesReducer.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  package.json
  src/actions/accommodationFacilitiesActions.js
  src/components/Accommodations/RoomCard.jsx
  src/components/Accommodations/UploadImage.jsx
  src/components/Accommodations/UploadRoomImage.jsx
  src/components/Accommodations/servicesCard.jsx
  src/components/profile/Nav.links.jsx
  src/components/user/userRole.jsx
  src/layouts/main.layout.jsx
  src/reducers/AccommodationFacilityReducer.js
  src/reducers/index.js
  src/styles/createAccommodation.js
  src/views/creating_accommodation_facilities/AccommodationFacility.jsx
  src/views/creating_accommodation_facilities/CreateAccommodation.jsx
Labels: completed, ready for review

#33 #169817832 : user edit trip request
  __mockData__/tripRequest-mock-data.js
  __tests__/tripRequestTest/tripRequestAction.test.js
  __tests__/tripRequestTest/tripRequestView.test.js
  __tests__/userTripRequests/actions.test.js
  __tests__/userTripRequests/reducers.test.js
  __tests__/userTripRequests/tripRequest.view.test.js
  src/actions/requests/tripRequestsAction.js
  src/actions/tripRequestAction.js
  src/reducers/trip_requests/tripRequestsReducers.js
  src/views/trip_requests/userTripRequest.view.jsx
  src/views/triprequest.view.jsx
Labels: completed, ready for review

#37 fix(create-accommodation-fix)
  README.md
  src/components/Accommodations/RoomCard.jsx
  src/styles/createAccommodation.js
  src/views/creating_accommodation_facilities/CreateAccommodation.jsx
Labels: ready for review

#35 #69817828 trip request search
  __mockData__/tripRequest-mock-data.js
  __tests__/approvals_table.js/approval.table.action.test.js
  __tests__/approvals_table.js/approvalsTable.test.js
  __tests__/approvals_table.js/tripRequest.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/signup/ActivateUser.view.test.js
  __tests__/tripRequestTest/tripRequestForm.test.js
  __tests__/tripRequestTest/tripRequestView.test.js
  __tests__/userTripRequests/actions.test.js
  __tests__/userTripRequests/tripRequests.view.test.js
  package.json
  src/actions/approval.table.js
  src/actions/requests/tripRequestsAction.js
  src/components/approvals_table/approval.table.jsx
  src/components/approvals_table/trip.request.jsx
  src/reducers/approval.table.reducer.js
  src/views/creating_accommodation_facilities/CreateAccommodation.jsx
  src/views/trip_requests/userTripRequests.view.jsx
Labels: completed, ready for review

#30 #169817840 Users should be able to book an accommodation facility
  __tests__/booking/actions.test.js
  __tests__/booking/booking.view.test.js
  __tests__/booking/reducers.test.js
  __tests__/booking/select.component.test.js
  __tests__/main.layout.test.js
  __tests__/userTripRequests/reducers.test.js
  __tests__/userTripRequests/tripRequest.view.test.js
  src/actions/UserRoleSettingAction.js
  src/actions/booking/accommodation.action.js
  src/components/App.jsx
  src/components/common/Select.component.jsx
  src/layouts/main.layout.jsx
  src/reducers/accommodations/accomodation.reducers.js
  src/reducers/index.js
  src/reducers/trip_requests/tripRequestsReducers.js
  src/styles/index.scss
  src/theme.js
  src/views/accommodations/booking.view.jsx
  src/views/signup/activate_user.view.jsx
  src/views/signup/signup.view.jsx
  src/views/trip_requests/userTripRequest.view.jsx
  src/views/trip_requests/userTripRequests.view.jsx
Labels: ready for review

#39 #171996626 add not found page
  src/layouts/default.layout.jsx
  src/layouts/main.layout.jsx
  src/styles/index.scss
  src/views/404.view.jsx
Labels: completed, ready for review

#40 #171974960 Users should be able to search in their trip requests
  __tests__/approvals_table.js/approval.table.action.test.js
  __tests__/approvals_table.js/approval.table.reducer.test.js
  __tests__/components/__snapshots__/editProfile/__snapshots__/top.navbar.test.js.snap
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/main.layout.test.js
  __tests__/main_layout/main.layout.action.test.js
  __tests__/main_layout/main.layout.reducer.test.js
  __tests__/userTripRequests/actions.test.js
  __tests__/userTripRequests/reducers.test.js
  src/actions/approval.table.js
  src/actions/main.layout.action.js
  src/actions/requests/tripRequestsAction.js
  src/components/approvals_table/approval.table.jsx
  src/components/profile/Nav.links.jsx
  src/components/profile/Profile.jsx
  src/components/profile/top.nav.bar.jsx
  src/components/user/userRole.jsx
  src/components/usermanagements/UserManagement.jsx
  src/helpers/titleGenerator.js
  src/layouts/main.layout.jsx
  src/reducers/approval.table.reducer.js
  src/reducers/index.js
  src/reducers/main_layout/main.layout.reducer.js
  src/reducers/trip_requests/tripRequestsReducers.js
  src/views/404.view.jsx
  src/views/creating_accommodation_facilities/CreateAccommodation.jsx
  src/views/trip_requests/userTripRequests.view.jsx
  src/views/triprequest.view.jsx
Labels: completed, ready for review

#38 #171988240 User can logout
  __tests__/components/__snapshots__/editProfile/__snapshots__/user.profile.test.js.snap
  __tests__/components/__snapshots__/editProfile/user.profile.test.js
  __tests__/loginTest/signinAction.test.js
  src/actions/logoutAction.js
  src/actions/signInAction.js
  src/components/auth/Login.jsx
  src/components/profile/userProfile.jsx
  src/views/SideNavBar.js
Labels: ready for review

#43 #172026937 remove duplicated line of code
  __tests__/components/__snapshots__/editProfile/__snapshots__/user.profile.test.js.snap
  __tests__/main.layout.test.js
  src/views/creating_accommodation_facilities/CreateAccommodation.jsx
Labels: completed, ready for review
