Repository andela/blackninjas-frontend, pull requests merged in 2020-02, with the labels that each got.

#4 #169817804:redux setup
  __mockData__/redux-mock-data.js
  __tests__/App.test.js
  __tests__/Welcome.test.js
  __tests__/actionsTest/homeActions.test.js
  __tests__/home.test.js
  __tests__/reducersTest/homeReducer.test.js
  package.json
  src/actions/homeActions.js
  src/components/App.jsx
  src/components/Welcome.jsx
  src/index.js
  src/reducers/homeReducer.js
  src/reducers/index.js
  src/store/index.js
  src/views/HomeRedux.js
Labels: completed, ready

#8 #171074504 Implementing nested routes
  __tests__/App.test.js
  __tests__/default.layout.test.js
  __tests__/main.layout.test.js
  __tests__/views/signin.view.test.js
  __tests__/views/signup.view.test.js
  src/components/App.jsx
  src/layouts/default.layout.jsx
  src/layouts/main.layout.jsx
  src/views/signin.view.jsx
  src/views/signup.view.jsx
  webpack.dev.js
Labels: completed, ready for review

#7 #169817814 User should login with email and Password
  .codeclimate.yml
  .gitignore
  __mockData__/PrivateRoute.mock.js
  __mockData__/redux-mock-data.js
  __mockData__/signin-mock-data.js
  __tests__/Footer.test.js
  __tests__/Login.test.js
  __tests__/PrivateRoute.test.js
  __tests__/View.login.test.js
  __tests__/View.welcome.test.js
  __tests__/Welcome.test.js
  __tests__/actionsTest/homeActions.test.js
  __tests__/appTest/appReducer.test.js
  __tests__/default.layout.test.js
  __tests__/home.test.js
  __tests__/loginTest/signin.test.js
  __tests__/loginTest/signin.view.test.js
  __tests__/loginTest/signinAction.test.js
  __tests__/loginTest/signinReducer.test.js
  __tests__/reducersTest/homeReducer.test.js
  __tests__/views/signin.view.test.js
  jest.config.js
  package.json
  src/actions/homeActions.js
  src/actions/signInAction.js
  src/components/App.jsx
  src/components/Welcome.jsx
  src/components/auth/Login.jsx
  src/components/auth/ProtectedRoute.jsx
  src/components/general/footer.js
  src/helpers/verifyToken.js
  src/layouts/default.layout.jsx
  src/reducers/appReducer.js
  src/reducers/homeReducer.js
  src/reducers/index.js
  src/reducers/signInReducer.js
  src/store/index.js
  src/styles/login.scss
  src/styles/login/loginStyle.js
  src/views/HomeRedux.js
  src/views/LoginPage.js
  src/views/WelcomePage.js
  src/views/signin.view.jsx
  webpack.common.js
  webpack.dev.js
Labels: ready for review

#9 #169817815 Users should be able to log in using Facebook or Google
  Procfile
  __mockData__/PrivateRoute.mock.js
  __mockData__/signin-mock-data.js
  __tests__/SocialLogin/SocialLogin.test.js
  jest.config.js
  package.json
  src/assets/facebook-app-logo-1.png
  src/assets/google-icon-1.png
  src/components/App.jsx
  src/components/auth/Login.jsx
  src/components/auth/ProtectedRoute.jsx
  src/components/auth/SocialLogin.jsx
  src/layouts/main.layout.jsx
  webpack.common.js
Labels: ready for review

#15 #171304320:fixing frontend heroku error
  Procfile
  jest.config.js
  package.json
  server.js
  webpack.prod.js
Labels: completed, ready for review

#12 #169817812 user signup on barefoot nomad
  __tests__/App.test.js
  __tests__/country_selector.test.js
  __tests__/default.layout.test.js
  __tests__/main.layout.test.js
  __tests__/reducersTest/appReducer.test.js
  __tests__/signup/ActivateUser.view.test.js
  __tests__/signup/activateUserAction.test.js
  __tests__/signup/activateUserReducer.test.js
  __tests__/signup/confirm.view.test.js
  __tests__/signup/signup.view.test.js
  __tests__/signup/signupAction.test.js
  __tests__/signup/signupForm.test.js
  __tests__/signup/signupReducer.test.js
  __tests__/text_input.test.js
  __tests__/views/signup.view.test.js
  jest.config.js
  package.json
  src/actions/activateUserAction.js
  src/actions/signupAction.js
  src/components/auth/Login.jsx
  src/components/common/CountrySelector.component.jsx
  src/components/common/TextInput.component.jsx
  src/components/signup/signup_form.component.jsx
  src/index.html
  src/index.js
  src/layouts/default.layout.jsx
  src/layouts/main.layout.jsx
  src/reducers/activateUserReducer.js
  src/reducers/index.js
  src/reducers/signupReducer.js
  src/store/index.js
  src/styles/index.scss
  src/theme.js
  src/views/signup.view.jsx
  src/views/signup/activate_user.view.jsx
  src/views/signup/confirm.view.jsx
  src/views/signup/signup.view.jsx
Labels: completed, ready for review

#14 chore(fix signin) fixing login page
  src/components/auth/Login.jsx
  src/views/signin.view.jsx
Labels: completed, ready for review

#10 #169817816 view and edit user profile
  .babelrc
  .vscode/settings.json
  __mockData__/redux-mock-data.js
  __tests__/App.test.js
  __tests__/PrivateRoute.test.js
  __tests__/__resetPassword_test__/components/forgotPassowrd.test.js
  __tests__/__resetPassword_test__/components/resetPassword.test.js
  __tests__/actionsTest/editProfile/profile.test.js
  __tests__/components/__snapshots__/editProfile/ side.navbar.test.js
  __tests__/components/__snapshots__/editProfile/__snapshots__/top.navbar.test.js.snap
  __tests__/components/__snapshots__/editProfile/__snapshots__/upload.image.test.js.snap
  __tests__/components/__snapshots__/editProfile/__snapshots__/user.profile.test.js.snap
  __tests__/components/__snapshots__/editProfile/country.select.test.js
  __tests__/components/__snapshots__/editProfile/edit.profile.test.js
  __tests__/components/__snapshots__/editProfile/gender.select.test.js
  __tests__/components/__snapshots__/editProfile/languge.select.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/components/__snapshots__/editProfile/top.navbar.test.js
  __tests__/components/__snapshots__/editProfile/upload.image.test.js
  __tests__/components/__snapshots__/editProfile/user.profile.test.js
  __tests__/loginTest/signin.test.js
  __tests__/main.layout.test.js
  __tests__/reducersTest/editProfile/profile.reducer.test.js
  __tests__/signup/signupForm.test.js
  jest.config.js
  package.json
  src/actions/user.profile.action.js
  src/components/App.jsx
  src/components/profile/Nav.links.jsx
  src/components/profile/Profile.jsx
  src/components/profile/top.nav.bar.jsx
  src/components/profile/userProfile.jsx
  src/components/templates/CountrySelect.jsx
  src/components/templates/GenderSelect.jsx
  src/components/templates/LangugeSelect.jsx
  src/components/templates/UploadImage.jsx
  src/helpers/verifyToken.js
  src/layouts/default.layout.jsx
  src/layouts/main.layout.jsx
  src/reducers/index.js
  src/reducers/user.profile.reducer.js
  src/store/index.js
  src/styles/index.scss
  src/styles/profile/profile.scss
  src/views/SideNavBar.js
  webpack.prod.js
Labels: ready for review

#17 #171378094 fix error message and upload image loader
  src/actions/user.profile.action.js
  src/components/profile/Profile.jsx
  webpack.prod.js
Labels: completed, ready for review

#18 chore(fix social auth styling): fixing login page and signup page
  __tests__/SocialLogin/SocialLogin.test.js
  src/components/auth/Login.jsx
  src/components/auth/SocialLogin.jsx
  src/components/signup/signup_form.component.jsx
  src/views/signin.view.jsx
Labels: ready for review

#19 #171382393 edit user and get user information
  __tests__/actionsTest/editProfile/profile.test.js
  __tests__/components/__snapshots__/editProfile/nav.links.test.js
  __tests__/reducersTest/editProfile/profile.reducer.test.js
  src/actions/user.profile.action.js
  src/components/profile/Nav.links.jsx
  src/components/profile/Profile.jsx
  src/reducers/user.profile.reducer.js
Labels: completed, ready for review

#21 #169817817 Implement requests table
  __tests__/main.layout.test.js
  __tests__/signup/ActivateUser.view.test.js
  __tests__/userTripRequests/actions.test.js
  __tests__/userTripRequests/reducers.test.js
  __tests__/userTripRequests/tripRequest.view.test.js
  __tests__/userTripRequests/tripRequests.view.test.js
  package.json
  src/actions/requests/tripRequestsAction.js
  src/actions/signInAction.js
  src/components/common/TextInput.component.jsx
  src/components/profile/Nav.links.jsx
  src/layouts/main.layout.jsx
  src/reducers/index.js
  src/reducers/trip_requests/tripRequestsReducers.js
  src/views/trip_requests/userTripRequest.view.jsx
  src/views/trip_requests/userTripRequests.view.jsx
Labels: ready for review
